project_name: radicalvpn_manager
builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
release:
  draft: true
snapshot:
  name_template: "{{ .Version }}-{{.ShortCommit}}"
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'